title: Velvet Chapter
description: 
url: ""
baseurl: ""
markdown: kramdown

collections:
  chapters:
    output: true
    permalink: /novels/:path/

defaults:
  - scope:
      path: ""
      type: "chapters"
    values:
      layout: chapter

liquid:
  error_mode: warn
